# Generated by Django 5.0.6 on 2024-07-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_patientinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='adress',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='gender',
            field=models.CharField(default=6, max_length=6),
            preserve_default=False,
        ),
    ]
